version = 5

[[exclude]]
pattern = "config/*.php"
reason = "generated"

[[exclude]]
pattern = "bootstrap/*.php"
reason = "generated"

[[exclude]]
pattern = "app/View/Components/Install/Input.php"
reason = "generated"

[[exclude]]
pattern = "public/*.*"
reason = "others"

